import {
  pgTable,
  text,
  timestamp,
  integer,
  boolean,
  pgEnum,
} from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';

// Enums for status and roles
export const roleEnum = pgEnum('role', ['interviewee', 'interviewer']);
export const meetingStatusEnum = pgEnum('meeting_status', [
  'scheduled',
  'live',
  'completed',
]);

/**
 * CORE USER TABLE
 * Aligned with Better-Auth requirements
 * Using text IDs as Better-Auth generates them client-side
 */
export const user = pgTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified').notNull().default(false),
  image: text('image'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
});

/**
 * USER PROFILES
 * Extended profile information for Meetsense
 */
export const profile = pgTable('profile', {
  id: text('id').primaryKey(),
  userId: text('user_id')
    .notNull()
    .unique()
    .references(() => user.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  role: roleEnum('role').notNull().default('interviewee'),
  jobTitle: text('job_title'),
  experience: text('experience'), // e.g., "5 years"
  domain: text('domain'), // e.g., "Frontend", "Backend", "AI"
  preferredLanguage: text('preferred_language').default('English'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

/**
 * MEETINGS / INTERVIEWS
 * Tracks LiveKit sessions and participants
 */
export const meeting = pgTable('meeting', {
  id: text('id').primaryKey(),
  hostId: text('host_id')
    .notNull()
    .references(() => user.id, { onUpdate: 'cascade' }),
  guestId: text('guest_id').references(() => user.id, { onUpdate: 'cascade' }),
  status: meetingStatusEnum('status').notNull().default('scheduled'),
  startTime: timestamp('start_time').notNull(),
  endTime: timestamp('endTime'),
  transcriptUrl: text('transcript_url'),
  recordingUrl: text('recording_url'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

/**
 * INTERVIEW RESULTS
 * Scores and feedback report generated by AI/Interviewer
 */
export const interviewResult = pgTable('interview_result', {
  id: text('id').primaryKey(),
  meetingId: text('meeting_id')
    .notNull()
    .references(() => meeting.id, { onDelete: 'cascade' }),
  technicalScore: integer('technical_score'),
  communicationScore: integer('communication_score'),
  confidenceScore: integer('confidence_score'),
  overallScore: integer('overall_score'),
  feedbackReport: text('feedback_report'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

/**
 * RELATIONS
 */
export const userRelations = relations(user, ({ one, many }) => ({
  profile: one(profile, {
    fields: [user.id],
    references: [profile.userId],
  }),
  meetingsAsHost: many(meeting, { relationName: 'host' }),
  meetingsAsGuest: many(meeting, { relationName: 'guest' }),
}));

export const profileRelations = relations(profile, ({ one }) => ({
  user: one(user, {
    fields: [profile.userId],
    references: [user.id],
  }),
}));

export const meetingRelations = relations(meeting, ({ one, many }) => ({
  host: one(user, {
    fields: [meeting.hostId],
    references: [user.id],
    relationName: 'host',
  }),
  guest: one(user, {
    fields: [meeting.guestId],
    references: [user.id],
    relationName: 'guest',
  }),
  results: many(interviewResult),
}));
